### ISSUE TITLE
[Feature Request] Always Active Mode for Specific Notes

### ISSUE THREAD

**Issue by FelipeRearden** [Galacsh/obsidian-reading-view-enhancer#2]
Hello @Galacsh !!!!!

For some specific notes, I would like to have a way to keep the note **always with the collapse indicator ACTIVE** every time the note is open in Reading View.

### My Idea 

If we have an yaml/frontmatter parameter to indicate that this specific note will be always active in reading mode.

This approach is based on the plugin [Force View Note](https://github.com/bwydoogh/obsidian-force-view-mode-of-note) that uses the YAML to apply a specific view for a note.

```
---
obsidianUIMode: preview
---
```

I would like to have the same flexibility with this plugin :)

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by imeed166** [comment]
Similar but different to @FelipeRearden idea, I want a toggle in the setting to always enable the selector whenever the user switches to the reading view.

Thank again for the plugin, makes reading much easier.

**Comment by Galacsh** [comment]
Thanks for the ideas @FelipeRearden, @imeed166.

Yeah, I need this feature also! I will work on this soon :)  
But since I am new to Obsidian plugin development, it will take some time.

Thank you for requesting! 🙌

**Comment by FelipeRearden** [comment]
> Thanks for the ideas @FelipeRearden, @imeed166.

💙

> Yeah, I need this feature also! I will work on this soon :) 

Great. Thank you very much @Galacsh !!!!!

> But since I am new to Obsidian plugin development, it will take some time.

Welcome to our community :) 
There is a channel on Discord server where the developer help each other. Might be a good source of information :)

Have a great day!

**Comment by Galacsh** [comment]
To start, I've added settings tab to enable/disable this keyboard navigation/folding/unfolding feature.

In order to fix the bug that was present in the initial version, I made some changes to this latest version.

First, the **navigation / fold / unfold method has been changed as follows.**

In the latest version, you can select "blocks" by clicking a block and navigate between blocks using keyboard (Arrow Up/Down). This feature is inspired by Notion's block navigation. (In Notion, you can select a block by pressing `Escape` key or clicking on a button aside the block)
If there is a collapse-indicator in the block, it has been changed to fold/unfold the block.

As a result of using `registerMarkdownPostProcessor`, **commands to turn the selector on and off has been removed.**

Thanks for suggesting the idea of "always enable/disable selector".

**Comment by Galacsh** [comment]
Ah,, something went wrong.. I'll fix the issues and come back again 😂

**Comment by FelipeRearden** [comment]
> Fixed minor bug and released 0.1.1! closing again :)

Hello @Galacsh ! Just to let you know that the latest version does not have `styles.css`

Maybe thats is the reason that I am not seeing the **collapse indicators** and I was not able to execute the keyboard navigation :)

> BTW, I'll work on submitting this plugin tomorrow

**Comment by Galacsh** [comment]
From 0.1.1, since the style is manually injected in the `<head>...</head>`, the plugin doesn't need `styles.css`.

I've uploaded this video on the `README.md`. Check this out if this fits your needs.

https://user-images.githubusercontent.com/78684419/228733812-26bfa11a-f246-4153-83ea-eed9aae39753.mov

**Comment by FelipeRearden** [comment]
> From 0.1.1, since the style is manually injected in the `<head>...</head>`, the plugin doesn't need `styles.css`.
> 
> I've uploaded this video on the `README.md`. Check this out if this fits your needs.

@Galacsh thank you for the reply !

Let me ask you 2 questions to see if I understood correctly ...

1️⃣ From version 0.1.1 I have to execute a `click` operation before using the keyboard shortcuts ?


2️⃣ There is no support for Obsidian Mobile?

---

I am asking you this because my idea is to use your plugin 100% full keyboard hotkeys: open a note on Reading mode (make it the active note) and then hitting keyboard hotkeys to navigate between headers and callouts. 

Moreover I use Obsidian Mobile on a iPad with a mouse and keyboard. If possible, I would like to have the same workflow on iPad that I have on Desktop 🙏

Thanks for reading this, my idea is to share with you my workflow to see if fits on your plugin idea 

Let me know what you think !

Have a great day ☀️

**Comment by Galacsh** [comment]
Thanks for your sincere feedback😃

I'll add these two features in the next version:

1. Command: Select top block in the view
2. Settings > Disable block selector on mobile

Will these meet your needs?

**Comment by Galacsh** [comment]
No you're not gonna lose :) 

I'll be back with the Command included in next release!

@FelipeRearden

**Comment by FelipeRearden** [comment]
> No you're not gonna lose :) 
> 
> I'll be back with the Command included in next release!
> 
> @FelipeRearden 

That's great !!!!!

Thank you very much @Galacsh !!!!

**Comment by Galacsh** [comment]
@FelipeRearden would you check this #5 ?

Please leave a comment on that issue whether this new release meet your needs.
