### ISSUE TITLE
Auto select first row

### ISSUE THREAD

**Issue by TfTHacker** [Galacsh/obsidian-reading-view-enhancer#7]
Great plugin idea! Will be one of my favs.

I am curious if it would be possible for this plugin to auto-select the first block when switching into read view.

Great work!

**Comment by Galacsh** [comment]
Hellom @TfTHacker

> Great plugin idea! Will be one of my favs.

Happy to hear that 😃.

Since I'll be busy starting tomorrow, so it will take some time.  
But I'll let you know when I start working on this feature.

Thanks a lot for the great idea!

**Comment by Galacsh** [comment]
Sorry for the delay in updates.

I've added a feature that allows the selection of the topmost visible block on the view when switching into reading view (Instead of the first block).

After updating the plugin(^0.1.5), you can use this feature by enabling the "Auto-select top block" option.

Thank you.
